package services

import (
	"context"

	"github.com/surveyflow/be/internal/models"
	apperr "github.com/surveyflow/be/internal/pkg/errors"
	"github.com/surveyflow/be/internal/repository"
)

// AnalyticsService handles analytics queries.
type AnalyticsService struct {
	analyticsRepo repository.AnalyticsRepo
	surveyRepo    repository.SurveyRepo
}

// NewAnalyticsService creates a new AnalyticsService.
func NewAnalyticsService(analyticsRepo repository.AnalyticsRepo, surveyRepo repository.SurveyRepo) *AnalyticsService {
	return &AnalyticsService{
		analyticsRepo: analyticsRepo,
		surveyRepo:    surveyRepo,
	}
}

// GetSummary returns the analytics summary for a survey.
func (s *AnalyticsService) GetSummary(ctx context.Context, orgID, surveyID string) (*models.AnalyticsSummary, error) {
	// Verify org owns survey.
	survey, err := s.surveyRepo.GetByID(ctx, surveyID)
	if err != nil {
		return nil, apperr.Internal(err)
	}
	if survey == nil || survey.OrgID.String() != orgID {
		return nil, apperr.Forbidden()
	}

	return s.analyticsRepo.GetSummary(ctx, surveyID)
}

// GetQuestionStats returns stats for a specific question.
func (s *AnalyticsService) GetQuestionStats(ctx context.Context, orgID, surveyID, questionID string) (*models.QuestionStats, error) {
	// Verify org owns survey.
	survey, err := s.surveyRepo.GetByID(ctx, surveyID)
	if err != nil {
		return nil, apperr.Internal(err)
	}
	if survey == nil || survey.OrgID.String() != orgID {
		return nil, apperr.Forbidden()
	}

	// Find the question type.
	questionType := "text"
	for _, q := range survey.Structure.Questions {
		if q.ID == questionID {
			questionType = q.Type
			break
		}
	}

	return s.analyticsRepo.GetQuestionStats(ctx, surveyID, questionID, questionType)
}

// GetCrossTab returns cross-tabulation between two questions.
func (s *AnalyticsService) GetCrossTab(ctx context.Context, orgID, surveyID, rowQuestionID, colQuestionID string) (*models.CrossTabResult, error) {
	// Verify org owns survey.
	survey, err := s.surveyRepo.GetByID(ctx, surveyID)
	if err != nil {
		return nil, apperr.Internal(err)
	}
	if survey == nil || survey.OrgID.String() != orgID {
		return nil, apperr.Forbidden()
	}

	return s.analyticsRepo.GetCrossTab(ctx, surveyID, rowQuestionID, colQuestionID)
}

// GetDropoff returns dropoff analysis for a survey.
func (s *AnalyticsService) GetDropoff(ctx context.Context, orgID, surveyID string) ([]models.DropoffStep, error) {
	// Verify org owns survey.
	survey, err := s.surveyRepo.GetByID(ctx, surveyID)
	if err != nil {
		return nil, apperr.Internal(err)
	}
	if survey == nil || survey.OrgID.String() != orgID {
		return nil, apperr.Forbidden()
	}

	return s.analyticsRepo.GetDropoff(ctx, surveyID)
}

// GetAIInsights returns AI-generated insights for a survey.
func (s *AnalyticsService) GetAIInsights(ctx context.Context, orgID, surveyID string) (*models.AIInsights, error) {
	// Verify org owns survey.
	survey, err := s.surveyRepo.GetByID(ctx, surveyID)
	if err != nil {
		return nil, apperr.Internal(err)
	}
	if survey == nil || survey.OrgID.String() != orgID {
		return nil, apperr.Forbidden()
	}

	// For MVP, return placeholder. In production, would call AI service.
	return &models.AIInsights{
		Summary:         "Analytics summary will be generated by AI.",
		KeyFindings:     []string{"Insights will be available after AI analysis."},
		Recommendations: []string{"Enable AI analysis for detailed recommendations."},
		Sentiment:       "neutral",
		Themes:          []models.AITheme{},
		Anomalies:       []models.AIAnomaly{},
	}, nil
}
